### ISSUE TITLE
Bug. MouseScrollDown MouseScrollUp attack

### ISSUE THREAD

**Issue by deixman1** [joshfreitas1984/Bannerlord.FluidCombatNext#2]
I have bound OverheadAttackKey to MouseScrollDown and StabAttackKey to MouseScrollUp. When I try to attack from above, the character defend

**Comment by joshfreitas1984** [comment]
Can you post a screenshot of your binds for Actions and for FluidCombat?

**Comment by deixman1** [comment]
I removed the game
